### ISSUE TITLE
weird shi happening in console window

### ISSUE THREAD

**Issue by zix3r** [Taiga74164/SLA-Cheeto#1]
![image](https://github.com/Taiga74164/SLA-Cheeto/assets/43238887/3371dd7e-0945-41be-a10b-2da5a4349930)
also, im not really sure how im suppossed to change the options for the hack, the arrow keys dont work

**Comment by ipoligt** [comment]
how do u use it. i mean where did u past and what did u past

**Comment by Taiga74164** [comment]
using imgui now
