### ISSUE TITLE
hotkey toggle display

### ISSUE THREAD

**Issue by Dreant910** [Taiga74164/SLA-Cheeto#10]
can you add hotkey toggle to show the menu like F1 to show, F1 to hide hehe fullscreen player here

**Comment by BlawwNulled** [comment]
there's already that but with insert (ins)

**Comment by KD-77** [comment]
I already build but when i put insert,it don't happen anything

**Comment by Blawwdotexe** [comment]
did u already renamed the sololeveling.dll to winhttp.dll?

**Comment by KD-77** [comment]
not yet sir, i don't konw where it is and I don't know where to put it to

could you please explain or guide me step by step?

**Comment by Blawwdotexe** [comment]
follow this https://www.unknowncheats.me/forum/other-mmorpg-and-strategy/629982-compile-taiga-solev-cheeto.html
