### ISSUE TITLE
How do I inject the cheeto?

### ISSUE THREAD

**Issue by EnvyZeneke2** [Taiga74164/SLA-Cheeto#100]
I am really sorry for asking this question in "issues," but I have been trying to use this cheat, but I don't know how to inject the cheat. I am really confused. When I open the injector, which is in the bin folder, and I select the DLL file and stuff and press insert, nothing happens. Am I supposed to add the ImGui thing, and if I do, how? I am really confused, and I hope you don't mind me asking these questions.

**Comment by RiritoNinigaya** [comment]
You Can't Inject DLL, because this programs is not signing by default!!! 

You Need to Sign this programs to bypassing verifications xigncode3: [Link](https://www.unknowncheats.me/forum/anti-cheat-bypass/564170-bypassing-xigncode3.html)
