### ISSUE TITLE
if the game is use after several minutes it will crashed

### ISSUE THREAD

**Issue by philwiz** [Taiga74164/SLA-Cheeto#101]
![image](https://github.com/Taiga74164/SLA-Cheeto/assets/170083488/e4925b13-0d66-4815-909e-40ade75399c8)

**Comment by philwiz** [comment]
I just use some Damage hack

**Comment by philwiz** [comment]
I found out now, why
![image](https://github.com/Taiga74164/SLA-Cheeto/assets/170083488/ce11d52f-b512-4859-bf64-657c748a7e29)

**Comment by mrekyd** [comment]
What does it means?

**Comment by WaddlesADuck** [comment]
It is saying that the command executes commands from a attacker (Hacker 💀). But It might be a false positive... So what you can do is Make a Exception for that Folder... [Windows Security > Virus and Threat Protection Settings > Exclusions > Add or remove Exclusions > Add Exclution]. Volia Now It Might Work
