### ISSUE TITLE
DLL Detected by the anticheat

### ISSUE THREAD

**Issue by tyrezzz** [Taiga74164/SLA-Cheeto#107]
hi the dll is detected by the anticheat (i used your own injector and also another one but still detected), i don't have this kind of problem with other dll

**Comment by Elpredykador** [comment]
hola, perdona por la molestia me podrias decir que otros dll usas a mi me salta siempre el xingcode y no me deja usarlo y con otros programas no me funcionan

**Comment by TheMegafuji** [comment]
change the name of the dll and the executable file and it works
