### ISSUE TITLE
Much error when trying to build

### ISSUE THREAD

**Issue by Dalk2ness** [Taiga74164/SLA-Cheeto#11]
here my errors

![image](https://github.com/Taiga74164/SLA-Cheeto/assets/10178164/5f983b7b-0a7f-4ebd-b5ea-4fb3bc7a9e8c)

**Comment by BlawwNulled** [comment]
i know that you can solve all errors with https://github.com/Taiga74164/SLA-Cheeto/pull/9/commits/c32972f626246d9c63de697459c53001608563f7


but for me when i try to build it i get this (i already added path)
![Screenshot_2](https://github.com/Taiga74164/SLA-Cheeto/assets/63196748/aaa24885-d387-4d86-a14a-620af88e82e0)
