### ISSUE TITLE
Not Work

### ISSUE THREAD

**Issue by Kraton96** [Taiga74164/SLA-Cheeto#112]
The file is successfully loaded into the game, but shortly after, anticheat detects it and closes the program.

**Comment by mherrmann7** [comment]
Same problem, but this couls be an injector problem as well

**Comment by PCamp3** [comment]
> Same problem, but this couls be an injector problem as well

Yeah, i tried taiga injector, extreme and xenos, just crashed after login

**Comment by mherrmann7** [comment]
yep, pretty sure it's just detected

**Comment by Mykola182006** [comment]
как скачать чит?

**Comment by noambert** [comment]
Me paso lo mismo lo detecta, algún injector que les haya funcionado?

**Comment by ArchernarhZ** [comment]
same here, tried with different injector still crashed

**Comment by TAIGA25cm** [comment]
Все здорово только определяется античитом и выкидывает с ошибкой о подозрительно программе. Помоги нам пользоваться твоим творение)

**Comment by AdrienGirault** [comment]
> same here, tried with different injector still crashed

do you have the .dll file ?

**Comment by Ninjafreak759** [comment]
i downloaded the new update, but i cant seem to find the DLL. Am i doing something wrong?

**Comment by OldDeusX** [comment]
> i downloaded the new update, but i cant seem to find the DLL. Am i doing something wrong?

download the latest on > Actions > update 1.1.16 > build-artifact

**Comment by TAIGA25cm** [comment]
> i downloaded the new update, but i cant seem to find the DLL. Am i doing something wrong?

Тебе нужно немного научится пользоваться Visual studio)
