### ISSUE TITLE
Old Damage Hack Method

### ISSUE THREAD

**Issue by kzu404** [Taiga74164/SLA-Cheeto#113]
I was trying to bring back old feature of damage hack, with the aim of making damage multiple. here the code:
```
if (vars.CritHack.value()) {
CALL_ORIGIN(PIPHNBOBFEF_KBCIIEFLPGB_Hook, __this, app::ESpecialState__Enum::CriticalRate, 2i64, 99999999i64, 0i64, buffName, method);}
```
did i miss something? or this CriticalRate = 0x0000004b, need to change? thanks

**Comment by Aashu9912** [comment]
how and where do i have to use this hack can you tell me?
