### ISSUE TITLE
Lost

### ISSUE THREAD

**Issue by Addelynqt** [Taiga74164/SLA-Cheeto#114]
can anyone tell me how to convert these files to dll please? I'm a noob and have 0 coding experience 🥺

**Comment by raro739** [comment]
> can anyone tell me how to convert these files to dll please? I'm a noob and have 0 coding experience 🥺

you just need to compile it with vscode, but the hack is already detected until now.

**Comment by Aashu9912** [comment]
can you please a bit more elaborative how to do this is VS code and is this still available?
i have a little bit knowledge of coding but i did not understand which file needs to be compiles there are quite a lot of files in the src folder

**Comment by Aashu9912** [comment]
thank you very much
😍😍
