### ISSUE TITLE
needs an update maybe ? :V

### ISSUE THREAD

**Issue by vladdy0001** [Taiga74164/SLA-Cheeto#12]
thanks for the cheat it was awesome but today when i tried to play it didn't work so i built the new one and it also didn't work and gave me this xD 
![image](https://github.com/Taiga74164/SLA-Cheeto/assets/108419963/39bdd271-f03a-4ba9-9f71-2fd82928ab7d)

**Comment by Taiga74164** [comment]
console logs doesnt have anything to do with the cheat. If the menu doesnt show then you may have to turn of external overlays.

**Comment by vladdy0001** [comment]
okay thanks <3
