### ISSUE TITLE
Successfully injected but still got an error code

### ISSUE THREAD

**Issue by MrDrapiach** [Taiga74164/SLA-Cheeto#120]
After successfully injecting i see the menu and can open and close it with insert, login and start loading in, Then the game closes with this error.
OXE019101A
Error: This error occurs when a program unrelated to the game is run. A virus or Trojan infection could be the cause. Please scan and clean the entire PC with an anti-virus program and then run the game as administrator after reboot the PC.

I followed its steps and then tried again but it still happened, does that just mean the current version is detected and we need to wait for an update to the project?

**Comment by Taiga74164** [comment]
This repo is fully updated to the latest version. However, it does not provide any detection bypass. I'm strongly against publishing bypass on a public repo to prevent devs from patching it. Either you figure it out yourself or use forks of this project with bypass. A lot of them actually are posted in Unknowncheats
