### ISSUE TITLE
after login my account the game crashes

### ISSUE THREAD

**Issue by lordWhite15** [Taiga74164/SLA-Cheeto#134]
![issues](https://github.com/user-attachments/assets/313e192b-9b4b-4d53-bebd-762b71849dd0)

**Comment by kxrmm** [comment]
game updated ::

**Comment by lordWhite15** [comment]
> game updated ::
Is their any way to fix this?

**Comment by kxrmm** [comment]
wait for him to update it

**Comment by Halumm66** [comment]
Wie bekomme ich denn die dll?

**Comment by lordWhite15** [comment]
> wait for him to update it

Its not update its message when the game crashes and exist

**Comment by kxrmm** [comment]
> > wait for him to update it
> 
> Its not update its message when the game crashes and exist
game version updated thats why old 1.1.5.6 not working = crashing happened in past also
