### ISSUE TITLE
Error or Bug?

### ISSUE THREAD

**Issue by Cristofer543** [Taiga74164/SLA-Cheeto#18]
![image](https://github.com/Taiga74164/SLA-Cheeto/assets/152051773/d3ad095b-3fd7-493d-8b08-54d4738d21dd)

**Comment by Cristofer543** [comment]
![image](https://github.com/Taiga74164/SLA-Cheeto/assets/152051773/53196b9b-7cd6-483d-aa10-a1e8f59f92c3)
![image](https://github.com/Taiga74164/SLA-Cheeto/assets/152051773/db0bf4c9-8b54-4bd6-b236-b9858ea3c41c)
![image](https://github.com/Taiga74164/SLA-Cheeto/assets/152051773/6f9e9a4d-a684-4fdf-8840-c3d69e044319)


How to Fix?

**Comment by Taiga74164** [comment]
error for you not reading https://github.com/Taiga74164/SLA-Cheeto?tab=readme-ov-file#building
