### ISSUE TITLE
(Bug) instant die for using q ability of lee bora

### ISSUE THREAD

**Issue by Blawwdotexe** [Taiga74164/SLA-Cheeto#23]
[https://streamable.com/3ybzfh](url)

**Comment by Taiga74164** [comment]
lmao wtf

**Comment by Taiga74164** [comment]
Could you identify which one of those feature kills you? I don't have her so I can't test. I suspect Damage Hack or God Mode

**Comment by Blawwdotexe** [comment]
tested now and it seems to be damage hack

**Comment by ELJoOker2004** [comment]
> Could you identify which one of those feature kills you? I don't have her so I can't test. I suspect Damage Hack or God Mode

probably healing skill has a reversed effect, if damage hack is enabled, you will be damaged that amount

**Comment by ELJoOker2004** [comment]
because the same problem happens with Ju-Hui Lee. the skills that make an area of enhancement will one shot you

**Comment by ELJoOker2004** [comment]
because the same problem happens with Ju-Hui Lee. the skills that make an area of enhancement will one-shot you

**Comment by AllanRuncandel** [comment]
![Screenshot 2024-04-02 014157](https://github.com/Taiga74164/SLA-Cheeto/assets/165708657/234fdfdc-0860-4cb7-a529-b06b2c2ab20c)
Erorrr!!

**Comment by kzu404** [comment]
the Q skill (AOE) cause instant dead

**Comment by kzu404** [comment]
this is already fixed in new damage hack sir, you can close it
