### ISSUE TITLE
seeking informations

### ISSUE THREAD

**Issue by ELJoOker2004** [Taiga74164/SLA-Cheeto#25]
can i ask you about the logic of this program?
what is dll proxying and how do you make the game auto-load this dll.
I'd really be grateful if you mentioned any sources that talk about this topic

**Comment by ELJoOker2004** [comment]
because the unknowncheats forum was closed, I didn't find another place to ask, sorry if this isn't the suitable place to ask about this

**Comment by emoisback-again** [comment]
dll proxying , is you make a proxy between dll that game loaded..

Game need to load winhttp.dll, because its try to find at the same folder as exe first and not found, they tried to find it on windows system32 folder and load it, what you do, you proxied the dll by place dll same as exe folder, so when he tried to find needed dll at the same folder its found, then you dll load original needed dll and export it function to let game use original function through your dll..

**Comment by ELJoOker2004** [comment]
> dll proxying , is you make a proxy between dll that game loaded..
> 
> Game need to load winhttp.dll, because its try to find at the same folder as exe first and not found, they tried to find it on windows system32 folder and load it, what you do, you proxied the dll by place dll same as exe folder, so when he tried to find needed dll at the same folder its found, then you dll load original needed dll and export it function to let game use original function through your dll..

so basically we recreate the winhttp.dll with all it's functions but we add other functions so we can use also right?

**Comment by ELJoOker2004** [comment]
that actually looks undetectable, why don't we see this technique used much?

**Comment by emoisback-again** [comment]
it is detectable, just see what dll that exe loaded and find where it come from, not from system32 then its a hack,.

**Comment by Dreant910** [comment]
bro use google its your friend not here

**Comment by ELJoOker2004** [comment]
> bro use google its your friend not here

where is the problem in asking?
i already searched google and got the concept but I needed further info

**Comment by ELJoOker2004** [comment]
> it is detectable, just see what dll that exe loaded and find where it come from, not from system32 then its a hack,.

can't we just do the same by kernel32.dll?

**Comment by Taiga74164** [comment]
@ELJoOker2004 you seem familiar 💀

**Comment by ELJoOker2004** [comment]
> @ELJoOker2004 you seem familiar 💀

I'm an old fan XD, didn't know you will remember
