### ISSUE TITLE
How to use and build this guys? im beginner at coding

### ISSUE THREAD

**Issue by NaViNata** [Taiga74164/SLA-Cheeto#26]

**Comment by KXXXA** [comment]
https://github.com/Taiga74164/CommandMenu/tree/8ea4256f5cdd87388e45fef93a0a93d6b9490ca6
https://github.com/Taiga74164/imgui/tree/47fb633e73f69e1ba57cef16cd077ddc4d97f0ee
https://github.com/Neargye/magic_enum/tree/d63a9d63717640705c6c9654d68fa6575d39bab8
Drag them all into their respective folders in src/vendor and unzip them and edit PostBuildEvent in notepad (change path_to_game to your game path, for example C:\Program Files\Netmarble\Netmarble Game\sololv)

**Comment by NaViNata** [comment]
> https://github.com/Taiga74164/CommandMenu/tree/8ea4256f5cdd87388e45fef93a0a93d6b9490ca6 https://github.com/Taiga74164/imgui/tree/47fb633e73f69e1ba57cef16cd077ddc4d97f0ee https://github.com/Neargye/magic_enum/tree/d63a9d63717640705c6c9654d68fa6575d39bab8 Drag them all into their respective folders in src/vendor and unzip them and edit PostBuildEvent in notepad (change path_to_game to your game path, for example C:\Program Files\Netmarble\Netmarble Game\sololv), then press build in visual studio if the dll doesn't end up in your game folder after building, check SLA-Cheeto-main\x64\Release for winhttp.dll (drag the dll to your game folder)

![Screenshot (99)](https://github.com/Taiga74164/SLA-Cheeto/assets/161337781/b8099f4d-97df-46ec-856d-f36933f0b5b9)
like that??

**Comment by Logan327** [comment]
I'm really sorry, but I still don't understand how to use this build, where is the "PostBuildEvent" file? If I could ask for a video on how to do it exactly from scratch, but of course I will understand if it's too much to ask.

**Comment by NaViNata** [comment]
> https://github.com/Taiga74164/CommandMenu/tree/8ea4256f5cdd87388e45fef93a0a93d6b9490ca6 https://github.com/Taiga74164/imgui/tree/47fb633e73f69e1ba57cef16cd077ddc4d97f0ee https://github.com/Neargye/magic_enum/tree/d63a9d63717640705c6c9654d68fa6575d39bab8 Drag them all into their respective folders in src/vendor and unzip them and edit PostBuildEvent in notepad (change path_to_game to your game path, for example C:\Program Files\Netmarble\Netmarble Game\sololv), then press build in visual studio if the dll doesn't end up in your game folder after building, check SLA-Cheeto-main\x64\Release for winhttp.dll (drag the dll to your game folder)

what alternative program for visual studio?

**Comment by KXXXA** [comment]
no you extract what's inside the commandmenu folder that you extracted to the src/vendor/commandmenu folder

**Comment by KXXXA** [comment]
![like this](https://github.com/Taiga74164/SLA-Cheeto/assets/50681377/ea6e0361-55d5-483c-b435-a57be116a614)

**Comment by KXXXA** [comment]
> I'm really sorry, but I still don't understand how to use this build, where is the "PostBuildEvent" file? If I could ask for a video on how to do it exactly from scratch, but of course I will understand if it's too much to ask.

it's the cmd file inside the SLA Cheeto folder
![sla cheeto](https://github.com/Taiga74164/SLA-Cheeto/assets/50681377/dfb09ca6-d829-4037-80e2-96f64897ce0d)

**Comment by KXXXA** [comment]
you may have to build the project once inside vs to get it

**Comment by cheatplease** [comment]
can someone have a video peace hehe!!

**Comment by cheatplease** [comment]
> https://github.com/Taiga74164/CommandMenu/tree/8ea4256f5cdd87388e45fef93a0a93d6b9490ca6 https://github.com/Taiga74164/imgui/tree/47fb633e73f69e1ba57cef16cd077ddc4d97f0ee https://github.com/Neargye/magic_enum/tree/d63a9d63717640705c6c9654d68fa6575d39bab8 Drag them all into their respective folders in src/vendor and unzip them and edit PostBuildEvent in notepad (change path_to_game to your game path, for example C:\Program Files\Netmarble\Netmarble Game\sololv), then press build in visual studio if the dll doesn't end up in your game folder after building, check SLA-Cheeto-main\x64\Release for winhttp.dll (drag the dll to your game folder)

loooool its trueee AHAHAHHA tyyy

**Comment by cheatplease** [comment]
im gonna foc igris now

**Comment by Taiga74164** [comment]
there's action builds now. you don't have to build it yourself

**Comment by cheatplease** [comment]
thankyou so much i just it in directory of the game <3 tyty

**Comment by cheatplease** [comment]
btw its unbannable for now right??

**Comment by NaViNata** [comment]
> there's action builds now. you don't have to build it yourself
> 
> https://github.com/Taiga74164/SLA-Cheeto/actions

how to use this?
