### ISSUE TITLE
detected

### ISSUE THREAD

**Issue by yousefelnegery** [Taiga74164/SLA-Cheeto#27]
![Screenshot_5](https://github.com/Taiga74164/SLA-Cheeto/assets/141242727/f709c75f-3e59-4ccc-90a6-897cfb015fcd)
the hack is detected now
**the unknown cheats version is working fine Bytheway**

**Comment by Herodot0s** [comment]
Mine was perfectly working, and it's also the latest build

**Comment by iskandarCsc** [comment]
> Mine was perfectly working, and it's also the latest build

Everything is working for me except for the damage hack

**Comment by Taiga74164** [comment]
build latest

**Comment by yousefelnegery** [comment]
I don't know how to build it 
Can u upload it any where?
