### ISSUE TITLE
GUI Not Showing

### ISSUE THREAD

**Issue by dsheriyana** [Taiga74164/SLA-Cheeto#35]
i was build and inject dll to game dir. like this : ![image](https://github.com/Taiga74164/SLA-Cheeto/assets/50573020/f0e57a86-2f1b-44ea-b62e-7eeb4e5db346)

but the gui not showing when i press insert button

**Comment by JuliaanPy** [comment]
Yo try to name it 

"winhttp.dll"

**Comment by cheatplease** [comment]
did you fix?


> i was build and inject dll to game dir. like this : ![image](https://private-user-images.githubusercontent.com/50573020/319122060-f0e57a86-2f1b-44ea-b62e-7eeb4e5db346.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzY4NDQsIm5iZiI6MTcxMjEzNjU0NCwicGF0aCI6Ii81MDU3MzAyMC8zMTkxMjIwNjAtZjBlNTdhODYtMmYxYi00NGVhLWI2MmUtN2VlYjRlNWRiMzQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA5MjkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2OGI1ZThjZDM4N2EyZDJjNjgxMGI5YTU4YzQ0M2ViMDc0N2YyMWE5ODFhMDYyM2U0Nzk0MmQzZGIwYjBkNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._dTH3vZODttW3ze1aEWgiavY8IfOgLAe7YalZY6XgJg)
> 
> but the gui not showing when i press insert button

**Comment by JuliaanPy** [comment]
They changed the way of this to work you now need an dll injector

**Comment by cheatplease** [comment]
i use extreme injector but it banned too

**Comment by cheatplease** [comment]
up for those know how to work this again

**Comment by JuliaanPy** [comment]
wdym with banned?

**Comment by azzzz327** [comment]
> Yo try to name it
> 
> "winhttp.dll"

Sir, do you have any suggestions for the injector that should be used so that it is not detected by xigncode?

**Comment by cheatplease** [comment]
> > Yo try to name it
> > "winhttp.dll"
> 
> Sir, do you have any suggestions for the injector that should be used so that it is not detected by xigncode?

it cant use like xigncode detecting it then the application will close

**Comment by JuliaanPy** [comment]
soo then the only solution for this now is use the old dll from unknowncheats i guess we need to wait for Emo and Taiga

**Comment by GOOPYGOOP6936** [comment]
Sorry if this is a stupid question but where is the dll because i downloaded the zip and couldnt find it inside there

**Comment by JuliaanPy** [comment]
you have to build it on youre own

**Comment by GOOPYGOOP6936** [comment]
Oh damn its my first time doing this on pc thats why i was confused thanks ill work it out then

**Comment by JuliaanPy** [comment]
you can use the dll from the unknowncheats thread

**Comment by JuliaanPy** [comment]
from there you will get the dll instant and it will work

**Comment by ron256289** [comment]
you can remove unknown cheats?

**Comment by JuliaanPy** [comment]
wdym with that?

**Comment by ron256289** [comment]
the file is not added to the game folder after compilation

**Comment by JuliaanPy** [comment]
yeah cause you need an injector but every dll injector is blacklisted by their anticheat

**Comment by ron256289** [comment]
All that remains is to wait for a new anti-cheat bypass?

**Comment by ron256289** [comment]
what injector can you recommend?

**Comment by JuliaanPy** [comment]
idk i guess every injector is blacktlisted so i cant recommend any

**Comment by JuliaanPy** [comment]
okay he updated his post on unknowncheats he say dll proxy is now detected idk if he mean with detected the game will not work or the game will ban you

**Comment by cheatplease** [comment]
anyone have now?

**Comment by JuliaanPy** [comment]
anyone have now what?

**Comment by cheatplease** [comment]
the cheat bro...

**Comment by JuliaanPy** [comment]
idk if you read the the topic here completly but i said couple of times go to unknowncheats 
heres the link download 1.0.1 and put it in youre game folder
https://www.unknowncheats.me/forum/other-mmorpg-and-strategy/629636-solo-leveling-arise-cheeto.html

**Comment by cheatplease** [comment]
![image](https://github.com/Taiga74164/SLA-Cheeto/assets/165759802/2ebb6ae5-ce11-4c18-bf29-a4087600809e)

**Comment by cheatplease** [comment]
ok thankyou for assisting me bro be god with ya

**Comment by aobatr** [comment]
> what injector can you recommend?

I use Extreme Injector and it's work perfecly fine

**Comment by kidmllie** [comment]
> > what injector can you recommend?
> 
> I use Extreme Injector and it's work perfecly fine

i can`t install extreme injector cause antivirus detect . off it already in windows security but still it say 'file containt virus'

**Comment by JuliaanPy** [comment]
yeah youre right i checked the forum page and saw the new injecting method with extreme now it works perfect for me too

> > what injector can you recommend?
> 
> I use Extreme Injector and it's work perfecly fine

**Comment by JuliaanPy** [comment]
do you use windows defender or any extra anti virus 
cause i only use windows defender it was enough to turn it off
