### ISSUE TITLE
can't login via email

### ISSUE THREAD

**Issue by knixnkk** [Taiga74164/SLA-Cheeto#39]
please help

**Comment by knixnkk** [comment]
![cause](https://github.com/Taiga74164/SLA-Cheeto/assets/105402591/ea3a22b4-6db7-4c89-b6e6-29599b133a3a)
also got this when login via google email

**Comment by JuliaanPy** [comment]
how this is related to the cheat? i mean check youre task manager if anything suspecious is running in the background 
and look for it and try to remove it

**Comment by Santuary12** [comment]
me to

**Comment by Taiga74164** [comment]
disable disable web view
