### ISSUE TITLE
the dmg hack is so op

### ISSUE THREAD

**Issue by yousefelnegery** [Taiga74164/SLA-Cheeto#40]
can u make the dmg hack scale from 10000 to 1million 
it is better than huge numbers affecting gameplay

**Comment by kidmllie** [comment]
![photo_6082206473695380552_w](https://github.com/Taiga74164/SLA-Cheeto/assets/165815685/83d18327-7304-4399-bb03-3503b5ac6df1)
how to solve this

**Comment by meshwara** [comment]
> 
> ![photo_6082206473695380552_w](https://github.com/Taiga74164/SLA-Cheeto/assets/165815685/83d18327-7304-4399-bb03-3503b5ac6df1)
> how to solve this
> 
> 

Try Secure start, I think it solved the problem

**Comment by yousefelnegery** [comment]
i found a method to put a low number here is screenshots
![Screenshot_6](https://github.com/Taiga74164/SLA-Cheeto/assets/141242727/c3476986-3883-4aae-9076-ae25db8707a0)
![Screenshot_7](https://github.com/Taiga74164/SLA-Cheeto/assets/141242727/16ff86d8-a28a-47d2-8c0c-0cdcb9cfcb95)
