### ISSUE TITLE
problem and idk how to download and activate it pls helpe me

### ISSUE THREAD

**Issue by meliodaswoo** [Taiga74164/SLA-Cheeto#41]

**Comment by Taiga74164** [comment]
that’s not my issue

**Comment by meliodaswoo** [comment]
Cool Story Bro but the thing is I don’t wanna talk with scum like u lol

Joaquin ***@***.***> schrieb am Do. 4. Apr. 2024 um 00:57:

**Comment by Taiga74164** [comment]
then don’t waste your time here. why’d u even ask retard

**Comment by meliodaswoo** [comment]
Why do u getting so personal bastard why u so mad kiddo cause ur dumb
cheats are not working?

Joaquin ***@***.***> schrieb am Do. 4. Apr. 2024 um 01:00:

**Comment by Taiga74164** [comment]
you’re the dumb one here coz you can’t read instructions

**Comment by meliodaswoo** [comment]
Cause I’m German and don’t need to know ur fck language son of a bitch

Joaquin ***@***.***> schrieb am Do. 4. Apr. 2024 um 01:04:
