### ISSUE TITLE
Maybe remove Shadow Cooldown

### ISSUE THREAD

**Issue by xMugi** [Taiga74164/SLA-Cheeto#42]
So, for Shadow Ability, you need shards you get via Mission drops, but if you have "no Shadow CD Enabled", you can still summon Shadows even without having the resources, but it will error you out with "Error 14, insufficient shards" at the end of the Mission

so
-Have no Shadow CD enabled
-use it ingame, even if u dont have any solider shards
-error 14 insufficient shards at the end of the mission and you have to restart the game.

so just dont use "no Shadow CD" it ig

**Comment by vietnamghost95** [comment]
Just disable it in menu

**Comment by xMugi** [comment]
> Just disable it in menu

yea i know, i have usually everything disable only "No Cooldown" for normal skills

**Comment by Taiga74164** [comment]
still looking to improve it

**Comment by Taiga74164** [comment]
honestly not that far into the game so i can’t t even test it

**Comment by cheatplease** [comment]
> So, for Shadow Ability, you need shards you get via Mission drops, but if you have "no Shadow CD Enabled", you can still summon Shadows even without having the resources, but it will error you out with "Error 14, insufficient shards" at the end of the Mission
> 
> so -Have no Shadow CD enabled -use it ingame, even if u dont have any solider shards -error 14 insufficient shards at the end of the mission and you have to restart the game.
> 
> so just dont use "no Shadow CD" it ig

what are you using injector bro
