### ISSUE TITLE
New Patch still working?

### ISSUE THREAD

**Issue by adipay8** [Taiga74164/SLA-Cheeto#45]
![patch](https://github.com/Taiga74164/SLA-Cheeto/assets/74783441/975ff90f-5b1d-4f6d-8fb5-bb6428acbe56)

**Comment by adipay8** [comment]
i try still working

**Comment by azzzz327** [comment]
> i try still working

what injector do you use?

**Comment by azzzz327** [comment]
pls

**Comment by azzzz327** [comment]
Please :(
