### ISSUE TITLE
Bug with Mob Vacuum

### ISSUE THREAD

**Issue by Pulpasek** [Taiga74164/SLA-Cheeto#46]
So, when I have the "Mob Vacuum" option turned off, mobs continue to teleport to me, and when I finish the mission, the game freezes and the only option is to reset it. When "Mob Vacuum" is turned on the same thing happens

YouTube Video: https://www.youtube.com/watch?v=zknlOVbcsdw

**Comment by aobatr** [comment]
Yeah i got that too

**Comment by Taiga74164** [comment]
i had to leave earlier so i was rushing and forgot to add the check

**Comment by Pulpasek** [comment]
Ok, but if you fix turning on and off mob vacuum, will game freezing after finishing a mission be fixed too?

**Comment by Taiga74164** [comment]
idk my game never froze
