### ISSUE TITLE
Stuck on mission clear 

### ISSUE THREAD

**Issue by Youssix** [Taiga74164/SLA-Cheeto#50]
Sometimes, you are stuck on the character after having victory on the story mode.

always have to restart the game when it happens

**Comment by JuliaanPy** [comment]
Have the same issue sometimes 
but sometimes i can press "Escape" and ill go back to the main menu but the battle missions will not completed until you restarted youre game

**Comment by aobatr** [comment]
> Sometimes, you are stuck on the character after having victory on the story mode.
> 
> always have to restart the game when it happens

It's bug from the game. Not the Cheeto

**Comment by zyxee** [comment]
> Sometimes, you are stuck on the character after having victory on the story mode.
> 
> always have to restart the game when it happens

disable no cooldown shadow, and if that doesn't work, change your costume.
