### ISSUE TITLE
insert button didnt open gui

### ISSUE THREAD

**Issue by bratxemss** [Taiga74164/SLA-Cheeto#57]
![изображение_2024-04-05_130705045](https://github.com/Taiga74164/SLA-Cheeto/assets/91002197/ef2dff23-8e2e-4365-bad2-518d8aadbcbb)

That is my console log.
The cheat works, but when I hit the "insert" button, nothing shows up

**Comment by Taiga74164** [comment]
overlays

**Comment by bratxemss** [comment]
i dont undestand wth is that mean
