### ISSUE TITLE
Please Provide dump of solo leveling arise pc version so that i can understand what values you used and why

### ISSUE THREAD

**Issue by HakaishinShwet** [Taiga74164/SLA-Cheeto#6]
Reason is that i have android version dump and rooted device and can hide and run game guardian too so wanted to understand what values you used from pc dump perspective to change values of function. Understanding that will help me to find value in game guardian and test out stuff for educational purpose :-))

**Comment by Taiga74164** [comment]
il2cppdumper

**Comment by HakaishinShwet** [comment]
@Taiga74164 i dont have pc version installed and have not much idea about its extraction of il2cpp can you upload dump in file.io or some temp website and share link from which i can quickly download and test

**Comment by Taiga74164** [comment]
You mentioned:
> i have android version dump and rooted device and can hide and run game guardian too

but for "educational purposes" you cant look up il2cppdumper and dump the game yourself?

**Comment by HakaishinShwet** [comment]
@Taiga74164 i can dump even protected il2cpp for "Educational Purposes" issue is not that.Just that i dont have pc file because i dont play on it as i am max time in my linux and  as i play on phone plus dont have any experience of pc file extraction and dumping will need to take time and extract things so to save time and make things easy i asked for it and since you have that file with you so thought to simply ask you to temporarily upload it so that i can download and test somethings for "Educational Purpose". Sharing is caring my friend :-))
