### ISSUE TITLE
I am a beginner, how should I use this

### ISSUE THREAD

**Issue by cmljq** [Taiga74164/SLA-Cheeto#63]
I am a beginner, how should I use this

**Comment by tuey30716** [comment]
-build project
-open games
-inject .dll

**Comment by cmljq** [comment]
I just got the dll, haha, I want to know how to inject it? I didn't find the relevant knowledge? Are there any tutorials to watch?

**Comment by tuey30716** [comment]
Extreme Injector: https://www.unknowncheats.me/forum/general-programming-and-reversing/213038-extreme-injector-v3-7-a.html

Settings: ![image](https://github.com/Taiga74164/SLA-Cheeto/assets/110269230/545b8200-f481-49c9-942f-7150130352a4) (thanks EDiT for the settings)

_Originally posted by @menleev in https://github.com/Taiga74164/SLA-Cheeto/issues/54#issuecomment-2039188506_

**Comment by cmljq** [comment]
ok i complete it thanks you are so gooooood

**Comment by cmljq** [comment]
![Uploading IMG_0260.jpeg…]()
A sad thing happened last night, I can still report a mistake today. Why is thisaaaaa
