### ISSUE TITLE
[EntityManager.cpp:49] IsCharacterAlive returned false, Enemy: Dummy_gimmick probably died or some shit

### ISSUE THREAD

**Issue by Hiirooo** [Taiga74164/SLA-Cheeto#68]
in dungeon battle get crash
[EntityManager.cpp:49] IsCharacterAlive returned false, Enemy: Dummy_gimmick probably died or some shit

**Comment by Taiga74164** [comment]
that doesnt give me any info. tell me what features you have on and how did it happen
