### ISSUE TITLE
Dumb enemy option & damage hack 

### ISSUE THREAD

**Issue by Dreant910** [Taiga74164/SLA-Cheeto#7]
dumb enemy option sometimes fails 
The referenced script on this Behaviour (Game Object '<null>') is missing!
The referenced script on this Behaviour (Game Object '<null>') is missing!
The referenced script on this Behaviour (Game Object '<null>') is missing!

damage hack doesn't work when editing value (slider) ingame

**Comment by Taiga74164** [comment]
You can ignore the console and damage hack is inconsistent and works only on certain weapons
