### ISSUE TITLE
detection

### ISSUE THREAD

**Issue by bratxemss** [Taiga74164/SLA-Cheeto#74]
I have this error
![image](https://github.com/Taiga74164/SLA-Cheeto/assets/91002197/0b4364d9-be02-4f0d-85dd-cad584fee081)

I tryed injector.exe in Release-x64 folder as injector and Extreame injector too.

The application gives this error every time after logging into the account.

Im injecting in main .exe file in game folder

I have the latest version of both the cheat and the game.

everything worked in the morning of 11.04

**Comment by russelammen** [comment]
Yea it is now being detected

**Comment by russelammen** [comment]
Manual Map Injection works

![image](https://github.com/Taiga74164/SLA-Cheeto/assets/88464097/9d831ba5-f9f7-4d56-a695-40d640e30901)

**Comment by Rekidan12** [comment]
yup its detected, tried with several injector (extreme, xenos, GH)

**Comment by xMugi** [comment]
> change the title in source

is it possible, that for example the cheeto randomized the title itself every inject?

**Comment by Taiga74164** [comment]
> > change the title in source
> 
> 
> 
> is it possible, that for example the cheeto randomized the title itself every inject? 

yes i already did. really busy with other stuff so i haven't pushed.

**Comment by xMugi** [comment]
> > > change the title in source
> > 
> > 
> > is it possible, that for example the cheeto randomized the title itself every inject?
> 
> yes i already did. really busy with other stuff so i haven't pushed.

oh, thank you and no worries!

**Comment by PaunServos** [comment]
Still works for me you have to it auto inject on the exe and have the exe
name in the autoinject. Then you run the exe from the folder NOT the
launcher.

**Comment by KyrieArvin** [comment]
> change the title in source

which specific line should I change title in src? Sorry not sure where it sits.

Thank you!

**Comment by Hiirooo** [comment]
I think now detects again

**Comment by anony159** [comment]
yeah back to detecting it now

**Comment by Hiirooo** [comment]
![updt](https://github.com/Taiga74164/SLA-Cheeto/assets/43614981/36b70439-d03d-45f5-bd21-3ab39687d643)
last update this file :')
