### ISSUE TITLE
detected

### ISSUE THREAD

**Issue by Hiirooo** [Taiga74164/SLA-Cheeto#78]
![updt](https://github.com/Taiga74164/SLA-Cheeto/assets/43614981/4b5c50af-f750-411e-82da-85da929f36e9)
detected after update 2 files

**Comment by meshwara** [comment]
Any solution please ?

**Comment by anony159** [comment]
did u find a way to make it work?

**Comment by Hiirooo** [comment]
> did u find a way to make it work?
need bypass :')

**Comment by kzu404** [comment]
> > did u find a way to make it work?
> > need bypass :')

what bypass?

**Comment by anony159** [comment]
where did u find the bypass
