### ISSUE TITLE
works

### ISSUE THREAD

**Issue by Ironmetta** [Taiga74164/SLA-Cheeto#80]
I don't know if it can help ^^

version used:

[https://github.com/Taiga74164/SLA-Ch...72ec693b2702dc](https://github.com/Taiga74164/SLA-Cheeto/tree/7fd8bf59e0b086f7065238f66772ec693b2702dc)

modify gui.cpp:

https://imgur.com/a/0LUVZny

@Taiga74164

**Comment by Ironmetta** [comment]
I don't know how to tell you, I'm with SSR and it works

**Comment by SalehAlmallah** [comment]
upload dll file please
and witch injector

**Comment by Ironmetta** [comment]
There injector:
https://www.unknowncheats.me/forum/general-programming-and-reversing/213038-extreme-injector-v3-7-a.html
[SLA_Cheeto test.zip](https://github.com/Taiga74164/SLA-Cheeto/files/14997842/SLA_Cheeto.test.zip)

on the other hand I don't guarantee that it's 100% safe, I've been using it since yesterday

**Comment by Hackorman69** [comment]
> I don't know how to tell you, I'm with SSR and it works

name of the weapon can you tell me?

**Comment by Ironmetta** [comment]
![Capture d'écran 2024-04-16 160646](https://github.com/Taiga74164/SLA-Cheeto/assets/167203887/31fb13a8-cab7-4622-89de-61d4eeab1d0e)
I use everything

**Comment by anony159** [comment]
this works for me but only on abilities which i dont mind

**Comment by simmorin** [comment]
I tried to  : 
git clone https://github.com/Taiga74164/SLA-Cheeto
git reset --hard 7fd8bf59e0b086f7065238f66772ec693b2702dc
git submodule init
git submodule update

then i build the dll
then i inject with xtrem

finally when i tried to connect with mail the connection pop-up doesn't show
what am i messing can you help me ?

**Comment by SalehAlmallah** [comment]
could you upload your dll please

**Comment by simmorin** [comment]
![image](https://github.com/Taiga74164/SLA-Cheeto/assets/94856658/74d2cd96-4a36-41da-9ec2-96901644cf20)
When i got here and i git on "sign in with email" i got this : 
![image](https://github.com/Taiga74164/SLA-Cheeto/assets/94856658/7b7dce39-347f-450b-8d28-e9fda32b8c98)
After some wait the dll is detected

**Comment by Ironmetta** [comment]
> pourriez-vous télécharger votre dll s'il vous plaît

look above I put with the injector download link

**Comment by simmorin** [comment]
same bug with your dll

**Comment by Ironmetta** [comment]
> same bug with your dll

What injector do you use?

**Comment by simmorin** [comment]
xtrem 3.7.3

**Comment by Ironmetta** [comment]
extrem you fixed it well

![Sans titre](https://github.com/Taiga74164/SLA-Cheeto/assets/167203887/51f8e56d-fb1a-471c-95cc-6fdac9f1b33d)

**Comment by Taiga74164** [comment]
this is done already and own injector is implemented

**Comment by Taiga74164** [comment]
your version is way behind as well

**Comment by Taiga74164** [comment]
Also, People are able to inject latest commits by renaming some names

**Comment by Ironmetta** [comment]
@Taiga74164 yes I know that it is a lower version, because with the last commits its function does not even modify the same thing it does not pass

**Comment by Flowseal** [comment]
Working well. 
@simmorin comment hook or disable "Disable WebView" function

**Comment by albertn15** [comment]
> Working well. @simmorin comment hook or disable "Disable WebView" function

this using old version?

**Comment by albertn15** [comment]
did someone work using new version with edit some file?

**Comment by SalehAlmallah** [comment]
> Working well. @simmorin comment hook or disable "Disable WebView" function

could you tell us your specific method to make it work ?

**Comment by Flowseal** [comment]
@Taiga74164 the last working commit is 1be1ed1
next commits = detect

**Comment by Taiga74164** [comment]
> @Taiga74164 the last working commit is 1be1ed1
> 
> next commits = detect

yea coz of strings. i'm not gonna push an update since people are selling it already lol.

**Comment by anony159** [comment]
anyone kno how to update it
