### ISSUE TITLE
New versión 1.0.24

### ISSUE THREAD

**Issue by iHakup** [Taiga74164/SLA-Cheeto#82]
When i inject the dll crash the game

**Comment by SalehAlmallah** [comment]
same as you :(

**Comment by z3nDeL** [comment]
is anyone who  has group ? to help each other's case ?

**Comment by adipay8** [comment]
forget it
play normal

**Comment by mindthings7** [comment]
how do I create a new dll, I'm completely new to this(( I tried "visual studio" but couldn't

**Comment by anony159** [comment]
it doesnt work anymore and creator doesnt want to update coz other people apparently started selling it

**Comment by PlatinumKron** [comment]
it would be fair for the creator to sell it himself and it would be good for him and the rest in that situation

**Comment by z3nDeL** [comment]
> it would be fair for the creator to sell it himself and it would be good for him and the rest in that situation

yeah i agree to that, i hope give us taiga some update <3
