### ISSUE TITLE
Can i buy it? shame that people are selling it fuck those guys. but if youre willing to sell it im down

### ISSUE THREAD

**Issue by Rekidan12** [Taiga74164/SLA-Cheeto#83]
ive added you in dc username is(jyu**)

**Comment by Hackorman69** [comment]
well there is 1 more solution to just put dll file in unknown cheats without putting source files in github which is a win win situation coz the game is not very fun without this i hope for ur return taiga

**Comment by z3nDeL** [comment]
count me in please
