### ISSUE TITLE
missing manual-map.h

### ISSUE THREAD

**Issue by kzu404** [Taiga74164/SLA-Cheeto#84]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'manual-map.h': No such file or directory	Injector	E:\C# Repo\SLA-Cheeto\injector\src\inject.h	8

**Comment by Taiga74164** [comment]
sorry can't provide code.

**Comment by kzu404** [comment]
> sorry can't provide code.

ow okay so i just remove the inject from project to make it success build dll right?

**Comment by Taiga74164** [comment]
yeah. i'm only providing updates but not solutions to bypass detection.
