### ISSUE TITLE
what should i do now ?xD

### ISSUE THREAD

**Issue by vladdy0001** [Taiga74164/SLA-Cheeto#93]
![image](https://github.com/Taiga74164/SLA-Cheeto/assets/108419963/89cc121e-b8d5-44ad-946c-94e457772462)
 help

**Comment by Taiga74164** [comment]
some people are able to inject it just fine. if you don't know what you're doing use something else

**Comment by vladdy0001** [comment]
i tried 4 injecotrs but all still with the same error :*(
