### ISSUE TITLE
anti cheat?

### ISSUE THREAD

**Issue by Gktwo** [Taiga74164/SLA-Cheeto#95]
![faf359e1f6ec54e53bcbdc5384d1867d](https://github.com/Taiga74164/SLA-Cheeto/assets/52039418/eede5795-3b15-4c37-a56b-91e7c33037ad)

**Comment by Taiga74164** [comment]
find your own bypass. i'm not pushing it

**Comment by obitom0702** [comment]
hey absor for WW inactive
